---
# tasks file for joe-speedboat.vsphere_clone_vm
- name: Check if VM already esists
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_api_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
  register: vm_info
  ignore_errors: yes
  delegate_to: localhost

- name: Fail if VM already exists
  fail:
    msg: "The VM {{ vm_name }} already exists"
  when: vm_info is defined and vm_info.failed == False

- name: Clone VM from template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_api_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"
    cluster: "{{ cluster_name }}"
    datacenter: "{{ datacenter_name }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    template: "{{ template_name }}"
    networks:
      - name: "{{ vm_network }}"
        start_connected: True
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: "{{ scsi_type }}"
    disk:
      - size_gb: "{{ vm_disk_gb }}"
        datastore: "{{ datastore_name }}"
  delegate_to: localhost
