# tasks file for joe-speedboat.vsphere_clone_vm
---
- include_tasks: datastore_check_size.yml
  when: datastore_check_size
- include_tasks: clone_vm.yml
- include_tasks: power_up_vm.yml
  when: vm_power_up
- include_tasks: post_setup.yml
  when: vm_power_up
