---
# tasks/post_setup_scripts.yml
- name: expand post setup script {{ post_setup_template }}
  block:
  - name: Generate {{ post_setup_template }} setup commands from template
    template:
      src: "{{ post_setup_template }}.j2"
      dest: "/tmp/{{ post_setup_template }}.sh"

  - name: Push {{ post_setup_template }} commands to VM
    community.vmware.vmware_guest_file_operation:
      hostname: "{{ vcenter_api_url }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ validate_certs }}"
      vm_id: "{{ vm_name }}"
      vm_username: "{{ vm_username }}"
      vm_password: "{{ vm_password }}"
      copy:
        src: "/tmp/{{ post_setup_template }}.sh"
        dest: "/root/{{ post_setup_template }}.sh"
    delegate_to: localhost

  - name: Execute {{ post_setup_template }} commands inside VM
    community.vmware.vmware_vm_shell:
      hostname: "{{ vcenter_api_url }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ validate_certs }}"
      folder: "{{ vm_folder }}"
      vm_id: "{{ vm_name }}"
      vm_username: "{{ vm_username }}"
      vm_password: "{{ vm_password }}"
      vm_shell: "/bin/bash"
      vm_shell_args: "/root/{{ post_setup_template }}.sh >> /root/{{ post_setup_template }}.log 2>&1"
      wait_for_process: True
    delegate_to: localhost


